/* Trip budget widget. Drop <div data-trip-calc></div> on any page plus this script.
   Optional: data-tours="slug,slug" preselects tours, data-days="5", data-level="comfort".
   Daily rates = budget tables of /blog/skolko-stoit-otdyh-v-gruzii/ (nights = days, as there).
   The DATA block is generated by scripts/build-trip-calc.py (catalog prices + NBG rate). */
(function (root) {
  'use strict';
  /* gen:start */
  var DATA = {"rub": 32.4, "rateDate": "24.09.2026", "rateSrc": "Нацбанк Грузии", "tours": [{"slug": "ekskursiya-kazbegi-iz-tbilisi", "name": "Казбеги", "price": 175}, {"slug": "ekskursiya-kakheti-iz-tbilisi", "name": "Кахетия", "price": 170}, {"slug": "ekskursiya-mtskheta-iz-tbilisi", "name": "Мцхета", "price": 98}, {"slug": "ekskursiya-stary-tbilisi", "name": "Старый Тбилиси", "price": 135}, {"slug": "nochnaya-ekskursiya-tbilisi", "name": "Ночной Тбилиси", "price": 100}, {"slug": "ekskursiya-david-gareji", "name": "Давид-Гареджа", "price": 225}, {"slug": "degustatsiya-vina-kakheti", "name": "Дегустация вина", "price": 225}, {"slug": "ekskursiya-borjomi-iz-tbilisi", "name": "Боржоми", "price": 178}]};
  /* gen:end */
  // [min, max] in GEL. room = one double room per night; the rest per person per day
  var LEVELS = {
    eco: { room: [80, 150], food: [50, 75], transport: [7, 11], fun: [13, 22] },
    comfort: { room: [150, 200], food: [80, 125], transport: [12, 18], fun: [25, 42] },
    lux: { room: [400, 900], food: [133, 200], transport: [17, 33], fun: [67, 117] }
  };
  var LEVEL_NAMES = { eco: 'эконом', comfort: 'комфорт', lux: 'люкс' };
  var SIM = 20; // one local SIM per person
  var MAX_DAYS = 30;
  var MAX_PEOPLE = 12;
  var WA = 'https://wa.me/995511272623';

  function clamp(n, lo, hi) { n = Math.round(Number(n) || lo); return Math.min(hi, Math.max(lo, n)); }

  function calc(o) {
    var days = clamp(o.days, 1, MAX_DAYS);
    var people = clamp(o.people, 1, MAX_PEOPLE);
    var L = LEVELS[o.level] || LEVELS.eco;
    var rooms = Math.ceil(people / 2);
    var tours = o.tours || [];
    var tourPp = tours.reduce(function (s, p) { return s + (Number(p) || 0); }, 0);
    // a day spent on a guided tour has no separate city entertainment spend
    var funDays = Math.max(0, days - tours.length);
    var parts = {
      stay: [L.room[0] * rooms * days, L.room[1] * rooms * days],
      food: [L.food[0] * people * days, L.food[1] * people * days],
      transport: [L.transport[0] * people * days, L.transport[1] * people * days],
      fun: [L.fun[0] * people * funDays, L.fun[1] * people * funDays],
      sim: [SIM * people, SIM * people],
      tours: [tourPp * people, tourPp * people]
    };
    var total = [0, 0];
    Object.keys(parts).forEach(function (k) { total[0] += parts[k][0]; total[1] += parts[k][1]; });
    return { days: days, people: people, parts: parts, total: total,
      perDay: [Math.round(total[0] / days / people), Math.round(total[1] / days / people)] };
  }

  function fmt(n) { return String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ' '); }
  function range(r, sign) { return sign + fmt(r[0]) + (r[0] === r[1] ? '' : '–' + fmt(r[1])); }
  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return '&#' + c.charCodeAt(0) + ';'; }); }

  var CSS = '.tcw{margin:28px 0;padding:20px;border:1px solid #bbf7d0;border-radius:14px;background:#f0fdf4;font-size:15px;color:#1f2937}' +
    '.tcw .tc-h{margin:0 0 4px;font-size:21px;font-weight:800}.tcw .tc-sub{margin:0 0 16px;font-size:13px;color:#4b5563}' +
    '.tcw fieldset{border:0;margin:0 0 14px;padding:0}.tcw legend{font-weight:700;margin-bottom:6px}' +
    '.tcw .tc-row{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:14px}' +
    '.tcw .tc-num{display:flex;flex-direction:column;font-weight:700;gap:6px}' +
    '.tcw input[type=number]{font:inherit;padding:10px;border:1px solid #9ca3af;border-radius:8px;background:#fff;min-height:44px;width:100%;box-sizing:border-box}' +
    '.tcw .tc-opts{display:flex;flex-wrap:wrap;gap:8px}' +
    '.tcw .tc-opts label{display:flex;align-items:center;gap:6px;padding:8px 12px;border:1px solid #d1d5db;border-radius:999px;background:#fff;min-height:44px;cursor:pointer}' +
    '.tcw .tc-opts small{color:#6b7280}.tcw .tc-out{margin-top:6px;padding:16px;border-radius:12px;background:#fff}' +
    '.tcw .tc-total{font-size:26px;font-weight:800;color:#1A3D2E}.tcw .tc-rub,.tcw .tc-pp{color:#4b5563}' +
    '.tcw dl{display:grid;grid-template-columns:1fr auto;gap:4px 12px;margin:12px 0}.tcw dd{margin:0;text-align:right;font-weight:600}' +
    '.tcw .tc-wa{display:block;text-align:center;padding:14px;border-radius:10px;background:#1A3D2E;color:#fff;font-weight:700;text-decoration:none}' +
    '.tcw .tc-note{margin:10px 0 0;font-size:12px;color:#6b7280}';

  function render(box, n) {
    var pre = (box.getAttribute('data-tours') || '').split(',');
    var level = LEVELS[box.getAttribute('data-level')] ? box.getAttribute('data-level') : 'eco';
    var days = clamp(box.getAttribute('data-days') || 7, 1, MAX_DAYS);
    var id = function (s) { return 'tc' + n + '-' + s; };
    var levels = Object.keys(LEVELS).map(function (k) {
      var hint = { eco: 'гестхаус, кафе', comfort: '3* отель, рестораны', lux: 'бутик-отель, fine dining' }[k];
      return '<label><input type="radio" name="' + id('level') + '" value="' + k + '"' + (k === level ? ' checked' : '') + '> ' +
        LEVEL_NAMES[k].charAt(0).toUpperCase() + LEVEL_NAMES[k].slice(1) + ' <small>' + hint + '</small></label>';
    }).join('');
    var tours = DATA.tours.map(function (t) {
      return '<label><input type="checkbox" data-tour value="' + t.price + '" data-name="' + esc(t.name) + '"' +
        (pre.indexOf(t.slug) > -1 ? ' checked' : '') + '> ' + esc(t.name) + ' <small>₾' + t.price + '</small></label>';
    }).join('');
    var rows = [['stay', 'Жильё'], ['food', 'Еда'], ['transport', 'Транспорт'], ['fun', 'Развлечения'], ['tours', 'Экскурсии'], ['sim', 'SIM-карта']]
      .map(function (r) { return '<dt>' + r[1] + '</dt><dd data-out="' + r[0] + '"></dd>'; }).join('');
    box.className += ' tcw';
    box.innerHTML =
      '<p class="tc-h">Калькулятор бюджета поездки в Грузию</p>' +
      '<p class="tc-sub">Цены жилья, еды и транспорта — из наших таблиц бюджета, экскурсии — по прайсу. Итог — вилка «от–до».</p>' +
      '<div class="tc-row">' +
      '<label class="tc-num" for="' + id('days') + '">Дней<input id="' + id('days') + '" data-days type="number" min="1" max="' + MAX_DAYS + '" value="' + days + '" inputmode="numeric"></label>' +
      '<label class="tc-num" for="' + id('people') + '">Человек<input id="' + id('people') + '" data-people type="number" min="1" max="' + MAX_PEOPLE + '" value="2" inputmode="numeric"></label>' +
      '</div>' +
      '<fieldset><legend>Уровень</legend><div class="tc-opts">' + levels + '</div></fieldset>' +
      (tours ? '<fieldset><legend>Экскурсии с гидом <small>(цена с человека)</small></legend><div class="tc-opts">' + tours + '</div></fieldset>' : '') +
      '<div class="tc-out" aria-live="polite"><div class="tc-total" data-out="total"></div><div class="tc-rub" data-out="rub"></div>' +
      '<div class="tc-pp" data-out="pp"></div><dl>' + rows + '</dl>' +
      '<a class="tc-wa" data-lead="trip-calc" href="' + WA + '" target="_blank" rel="noopener">Отправить расчёт гиду в WhatsApp</a>' +
      '<p class="tc-note">Жильё — за ночь на двухместный номер, ночей = дней. Курс: 1 ₾ ≈ ' + DATA.rub +
      ' ₽ (' + (DATA.rateSrc || 'Нацбанк Грузии') + ', ' + DATA.rateDate + '). Перелёт не входит.</p></div>';
  }

  function init(box, n) {
    render(box, n);
    var $ = function (s) { return box.querySelector(s); };
    var out = function (k, v) { $('[data-out="' + k + '"]').textContent = v; };
    function update() {
      var d = $('[data-days]').value, p = $('[data-people]').value;
      if (d === '' || p === '') return; // keep last result while the field is being retyped
      var prices = [], names = [];
      box.querySelectorAll('[data-tour]:checked').forEach(function (i) {
        prices.push(i.value); names.push(i.getAttribute('data-name'));
      });
      var level = $('input[type=radio]:checked').value;
      var r = calc({ days: d, people: p, level: level, tours: prices });
      out('total', range(r.total, '₾'));
      out('rub', '≈ ' + fmt(r.total[0] * DATA.rub) + '–' + fmt(r.total[1] * DATA.rub) + ' ₽');
      out('pp', range(r.perDay, '₾') + ' в день на человека');
      Object.keys(r.parts).forEach(function (k) { out(k, range(r.parts[k], '₾')); });
      var msg = 'Здравствуйте! Расчёт с сайта: ' + r.days + ' дн., ' + r.people + ' чел., ' + LEVEL_NAMES[level] +
        (names.length ? ', туры: ' + names.join(', ') : '') + '. Итого ≈ ' + range(r.total, '₾') +
        '. Хочу уточнить даты и туры.';
      $('.tc-wa').href = WA + '?text=' + encodeURIComponent(msg);
    }
    // own event, not generate_lead: the page-level WhatsApp listener already counts the lead
    $('.tc-wa').addEventListener('click', function () {
      if (typeof root.gtag === 'function') root.gtag('event', 'trip_calc_whatsapp', { event_category: 'whatsapp' });
    });
    box.addEventListener('input', update);
    box.addEventListener('change', update);
    update();
  }

  var api = { calc: calc, LEVELS: LEVELS };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else {
    root.TripCalc = api;
    var run = function () {
      var boxes = document.querySelectorAll('[data-trip-calc]');
      if (!boxes.length) return;
      var st = document.createElement('style'); st.textContent = CSS; document.head.appendChild(st);
      boxes.forEach(function (b, i) { init(b, i); });
    };
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', run); else run();
  }
})(this);
